# Changes here will be overwritten by Copier
_commit: v1.2.0
_src_path: https://github.com/worldworm/copier-base-copier.git
answersfile_suffix: docker
copier_version: '9'
copyright_license: MIT
copyright_year_start: 2024
copyright_year_today: 2024
is_bp: false
is_ext: false
is_meta: false
need_trust: false
project_description: Copier template for docker projects.
project_emoji: 📋
project_name: copier-docker
ref_tech_url: https://github.com/moby/moby
repository_name: copier-docker
repository_provider: GitHub
repository_url: https://github.com/worldworm/copier-docker
repository_username: worldworm
warning_early_dev: false
